name: MirrorX Release

on:
  push:
    tags:
      - "v*.*.*"


jobs:
  BuildWheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.6
      - name: Install deps fro Pypi Release
        run: |
          pip -q install setuptools wheel twine
          pip -q install -r requirements.txt
      - name: Publish to pypi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
      - name: Sleep
        run: sleep 60
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with: 
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: token
          password: ${{ secrets.GH_TOKEN }}
      - name: Docker meta
        id: metaraw
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/iamliquidx/mirrorx
          tags: |
            type=semver,pattern={{version}}
      - name: Build and push LTS RAW
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64/v8
          push: true
          tags: ${{ steps.metaraw.outputs.tags }}
          labels: ${{ steps.metaraw.outputs.labels }}